pipeline:
  dco:
    image: algernon/drone-plugin-dco

  bootstrap:
    group: bootstrap
    image: algernon/debian-ci-builder:unstable
    commands:
      - autoreconf -i

  tls-certificates:
    group: bootstrap
    image: algernon/debian-ci-builder:unstable
    commands:
      - apt install -y openssl
      - cd tests/etc && ./gen-certs.sh

  stable-build:
    group: build
    image: algernon/debian-ci-builder:stable
    environment:
      - RCC_NETWORK_TESTS=1
      - RIEMANN_HOST=riemann
    commands:
      - apt install -y check protobuf-c-compiler libprotobuf-c-dev libgnutls28-dev libjson-c-dev lcov
      - install -d _build/stable
      - cd _build/stable
      - ../../configure --enable-silent-rules CFLAGS="-Wall -Wextra -O3 -g --coverage"
      - make
      - make coverage.info CK_VERBOSITY=normal
      - genhtml coverage.info | tail -n 3

  unstable-build:
    group: build
    image: algernon/debian-ci-builder:unstable
    environment:
      - RCC_NETWORK_TESTS=1
      - RIEMANN_HOST=riemann
    commands:
      - apt install -y check protobuf-c-compiler libprotobuf-c-dev libgnutls28-dev libjson-c-dev lcov
      - install -d _build/unstable
      - cd _build/unstable
      - ../../configure --enable-silent-rules CFLAGS="-Wall -Wextra -O3 -g --coverage"
      - make
      - make coverage.info CK_VERBOSITY=normal
      - genhtml coverage.info | tail -n 3

services:
  riemann:
    image: algernon/riemann
    environment:
      - RIEMANN_CONFIG=/drone/src/git.madhouse-project.org/algernon/riemann-c-client/tests/etc/riemann.config
      - RIEMANN_HOST=riemann
      - RIEMANN_TLS_KEY=/drone/src/git.madhouse-project.org/algernon/riemann-c-client/tests/etc/server.pkcs8
      - RIEMANN_TLS_CERT=/drone/src/git.madhouse-project.org/algernon/riemann-c-client/tests/etc/server.crt
      - RIEMANN_TLS_CACERT=/drone/src/git.madhouse-project.org/algernon/riemann-c-client/tests/etc/cacert.pem

    detach: true
