pipeline:
  dco:
    image: algernon/drone-plugin-dco

  bootstrap:
    image: algernon/debian-ci-builder:unstable
    commands:
      - autoreconf -i

  stable-build:
    group: build
    image: algernon/debian-ci-builder:stable
    commands:
      - apt install -y check protobuf-c-compiler libprotobuf-c-dev libgnutls28-dev libjson-c-dev
      - install -d _build/stable
      - cd _build/stable
      - ../../configure --enable-silent-rules CFLAGS="-Wall -Wextra -O3 -g"
      - make
      - make check

  unstable-build:
    group: build
    image: algernon/debian-ci-builder:unstable
    commands:
      - apt install -y check protobuf-c-compiler libprotobuf-c-dev libgnutls28-dev libjson-c-dev
      - install -d _build/unstable
      - cd _build/unstable
      - ../../configure --enable-silent-rules CFLAGS="-Wall -Wextra -O3 -g"
      - make
      - make check
