language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq check protobuf-c-compiler libprotobuf-c0-dev
before_script:
  - install -d m4
  - autoreconf -i
script:
  - ./configure --enable-silent-rules
  - make
  - make check
compiler:
  - gcc
  - clang
