language: c
before_install:
  - sudo pip install cpp-coveralls
  - wget http://aphyr.com/riemann/riemann_0.2.5_all.deb
  - sudo dpkg -i riemann*deb
  - sudo service riemann start
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq check protobuf-c-compiler libprotobuf-c0-dev
  - gem install ronn
before_script:
  - autoreconf -i
script:
  - ./configure --enable-silent-rules CFLAGS="-Wall -Wextra -O0 -g -pg  -fprofile-arcs -ftest-coverage" LDFLAGS="-pg"
  - make
  - make check
compiler:
  - gcc
  - clang
after_success:
  - coveralls --exclude tests --exclude src --exclude lib/riemann/proto --exclude lib/riemann/*.h
